### ISSUE TITLE
Add 3.3v+ gnd connector towards head for expansion board

### ISSUE THREAD

**Issue by keionbis** [OperationSmallKat/SmallKat-Motherboard#8]
@madhephaestus wants to be able add on secondary esp32 board in the head, this needs power and should, should only need a connector for 3.3v and gnd. 

This can use the same molex pico blade connector from the battery serial

**Comment by madhephaestus** [comment]
do you have a suggestion of a good module for this?

**Comment by keionbis** [comment]
depends what you actally want from it, If its just a camera it would be something like the espeye or a derivative board. If you want other things like an imu then we would probably need to spin up a board for it

**Comment by madhephaestus** [comment]
yeah, ok. This one? https://www.mouser.com/ProductDetail/Espressif-Systems/ESP-EYE?qs=l7cgNqFNU1iWrlpTZmwCRA%3D%3D

**Comment by keionbis** [comment]
Might be worth using this one instead https://www.mouser.com/ProductDetail/M5Stack/U082?qs=81r%252BiQLm7BTFg2IRCU1YKQ%3D%3D
It gives us a convenient place to give it 3.3v with the connector at the bottom

**Comment by madhephaestus** [comment]
ok, cool

**Comment by keionbis** [comment]
added in the newest board rev
